#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

use yii\helpers\ArrayHelper;

defined('YII_DEBUG') or define('YII_DEBUG', true);

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = ArrayHelper::merge(
    require(__DIR__ . '/config/web.php'),
    require(__DIR__ . '/config/console.php')
);

unset($config['components']['errorHandler']);
unset($config['components']['user']);
unset($config['components']['request']);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
